version: 2.1

orbs:
  hugo: circleci/hugo@0.3

workflows:
  main:
    jobs:
      - hugo/build:
          version: "0.58.2"
          source: "src/"
          html-proofer: true
      - deploy:
          requires:
            - hugo/build
          filters:
            branches:
              only: master
jobs:
  deploy:
    docker:
      - image: cibuilds/hugo:0.58.2
    steps:
      - attach_workspace:
          at: src
      - add_ssh_keys
      - run: |
          echo 'sweb0.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHyIA/VJN9GHUeYUvauk+sGsQcvk8FpXErixwvgqQmW1pdje/Vo4RyAAskzdgoR+HUYOWM1gLW7ZFZHL8F//sqw=' >> ~/.ssh/known_hosts
          rsync -va --delete src/public/ root@sweb0.revidian.net:/static-websites/felicianotech/www/public_html
