version: 2.1

orbs:
  hugo: circleci/hugo@0.3

workflows:
  main:
    jobs:
      - hugo/build:
          version: "0.56.0"
          source: "src/"
          html-proofer: true
      - deploy:
          requires:
            - hugo/build
          filters:
            branches:
              only: master
jobs:
  deploy:
    docker:
      - image: cibuilds/hugo:0.56.0
    steps:
      - attach_workspace:
          at: src
      - add_ssh_keys
      - run: |
          echo 'web01.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJiGRY6N9WYQ0vy6cTiwAgNbc6ueJmVo/EafBtmT7bcD6cQMbipYM/KfYQ2lCn2TxqWepZKYoyoVQXgArycCOns=' >> ~/.ssh/known_hosts
          rsync -va --delete src/public/ staticweb@web01.revidian.net:www/www.feliciano.tech/public_html
