version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.20.6
    working_directory: ~/feliciano.tech
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/feliciano.tech/src/
      - run:
          name: "Test Website"
          command: htmlproofer ~/feliciano.tech/src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external | tee $CIRCLE_ARTIFACTS/htmlproofer-results.txt; exit ${PIPESTATUS[0]}
      - add_ssh_keys
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'web01.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJiGRY6N9WYQ0vy6cTiwAgNbc6ueJmVo/EafBtmT7bcD6cQMbipYM/KfYQ2lCn2TxqWepZKYoyoVQXgArycCOns=' >> ~/.ssh/known_hosts
              rsync -va --delete src/public/ staticweb@web01.revidian.net:www/feliciano.tech/public_html
            fi
