version: 2.1

orbs:
  strawberry: hubci/strawberry@0.6

workflows:
  main:
    jobs:
      - strawberry/build:
          version: "0.21.0"
          source: "src"
          html-proofer: true
      - deploy:
          requires:
            - strawberry/build
          filters:
            branches:
              only: trunk
  nightly:
    # This nightly workflow is to rebuild the site in case there are blog posts
    # that need to be published
    triggers:
      - schedule:
          # Everyday at 10am UTC or 5/6am Eastern
          cron: "0 10 * * *"
          filters:
            branches:
              only: trunk
    jobs:
      - strawberry/build:
          version: "0.21.0"
          source: "src"
          html-proofer: true
      - deploy:
          requires:
            - strawberry/build
          filters:
            branches:
              only: trunk

jobs:
  deploy:
    docker:
      - image: hubci/strawberry:0.21.0
    steps:
      - attach_workspace:
          at: src
      - add_ssh_keys
      - run:
          name: "Deploy to Revidian Cloud"
          command: |
            echo 'web0.atl.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE16slz1okRPeUhxIpzBCn9rHqjk51ylxEYlYXvblswcxOQ0rPyAX6N8Bd2pnsh99xce/jaX2KJHPLPCc+zAXTg=' >> ~/.ssh/known_hosts
            rsync -va --delete src/public/ root@web0.atl.revidian.net:/gfs-vols/static-vol/felicianotech/www/public_html
