baseurl = "https://www.Feliciano.Tech/"
title = "Feliciano.Tech"
languageCode = "en-us"
theme = "ftech-2023"

googleAnalytics = "G-367692373"
disqusShortname = "felicianotechcom"

enableEmoji = true

[params]
	description	= "This is my (Ricardo N Feliciano) personal website. A place for me to blog and share my projects."

[blackfriday]
	hrefTargetBlank	=	true

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[[menu.main]]
	name	= "Home"
	url		= "/"
	weight	= -1

[[menu.main]]
	name	= "Blog"
	url		= "/blog/"
	weight	= 5

[[menu.main]]
	name	= "Projects"
	url		= "/projects/"
	weight	= 10

[[menu.main]]
	name	= "About"
	url		= "/about/"
	weight	= 20


[[menu.social]]
    url = "https://twitter.com/FelicianoTech"
    name = "twitter"
    weight = 30

[[menu.social]]
    name = "github"
    url = "https://github.com/FelicianoTech"
    weight = 20

[[menu.social]]
    name = "mastodon"
    url = "https://nanobyte.cafe/@FelicianoTech"
    weight = 10

[[menu.social]]
    name = "dev"
    url = "https://dev.to/felicianotech"
    weight = 40

[[menu.social]]
    name = "instagram"
    url = "https://www.instagram.com/FelicianoTech/"
    weight = 50

[[menu.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ricardofeliciano"
    weight = 60
