baseurl = "https://Feliciano.Tech/"
title = "Feliciano.Tech"
languageCode = "en-us"
theme = "feliciano.tech-2017"

googleAnalytics = "UA-66191620-1"
disqusShortname = "felicianotechcom"

enableEmoji = true

[blackfriday]
	hrefTargetBlank	=	true

[[menu.main]]
	name	= "Home"
	url		= "/"
	weight	= -1

[[menu.main]]
	name	= "Blog"
	url		= "/blog/"
	weight	= 5

[[menu.main]]
	name	= "Projects"
	url		= "/projects/"
	weight	= 10

[social]
	twitter = "FelicianoTech"
